version: "3"

services:
  discoverer:
    restart: always
    image: ghcr.io/dazwilkin/consul-sd-cloudrun:ee9d11f790bff7db9b22cf8de333fa7e1dc52d0c
    container_name: discoverer
    command:
    - --consul=consul:8500
    - --project_ids=...
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/client_secrets.json
    volumes:
      - /home/userid/.config/gcloud/application_default_credentials.json:/secrets/client_secrets.json

  consul:
    restart: always
    image: docker.io/consul:1.11.0-beta
    container_name: consul
    expose:
    - "8500" # HTTP API|UI
    ports:
    - 8500:8500/tcp
    - 8600:8600/udp

  prometheus:
    restart: always
    depends_on:
      - consul
    image: docker.io/prom/prometheus:v2.31.0
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - "9090"
    ports:
      - 9090:9090

  cadvisor:
    restart: always
    image: gcr.io/google-containers/cadvisor:v0.36.0
    container_name: cadvisor
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      # Default location
      # - "/var/lib/docker/:/var/lib/docker:ro"
      # Snap location
      - "/var/snap/docker/current:/var/lib/docker:ro"
    expose:
      - "8080"
    ports:
      - 8089:8080
