name: build

on:
  push:
    branches:
      - main

jobs:
  ackal:
    name: consul-sd-cloudrun
    runs-on: ubuntu-latest
    env:
      IMAGE: dazwilkin/consul-sd-cloudrun
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        uses: docker/setup-buildx-action@v3
      - name: QEMU
        uses: docker/setup-qemu-action@v3
      - name: login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}
      - name: Get kernel version
        run: echo "VERSION=$(uname --kernel-release)" >> ${GITHUB_ENV}
      - name: Buildx Multi-platform Linux Docker Images
        id: docker-build-push-multi-platform
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v7,linux/arm64
          file: ./Dockerfile
          build-args: |
            TOKEN=${{ secrets.GHCR }}
            VERSION=${{ env.VERSION }}
            COMMIT=${{ github.sha }}
          tags: ghcr.io/${{ env.IMAGE }}:${{ github.sha }}
          push: true
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
      - name: Write signing key to disk (only needed for `cosign sign --key`)
        run: echo "${{ secrets.SIGNING }}" > ./cosign.key
      - name: Sign container image
        run: |
          DIGEST=${{ steps.docker-build-push-multi-platform.outputs.digest }}
          cosign sign \
          --yes \
          --key=./cosign.key \
          --annotations="repo=${{ github.repository }}" \
          --annotations="workflow=${{ github.workflow }}" \
          --annotations="commit=${{ github.sha }}" \
          --annotations="version=${{ env.VERSION }}" \
          ghcr.io/${{ env.IMAGE }}@${DIGEST}
        env:
          COSIGN_PASSWORD: ""
      - name: revise occurrences of the image
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"

          for FILENAME in "./README.md" "./docker-compose.yml"
          do
            echo "Replacing: ${IMAGE}"
            sed \
            --in-place \
            "s|${IMAGE}:[0-9a-f]\{40\}|${IMAGE}:${{ github.sha }}|g" \
            ${FILENAME}
            git add ${FILENAME}
          done

          git commit --message "GitHub Actions update image references"
          git push origin main
