name: build

on:
  push:
    branches:
      - main

jobs:
  ackal:
    name: consul-sd-cloudrun
    runs-on: ubuntu-20.04
    env:
      IMAGE: dazwilkin/consul-sd-cloudrun
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup
        uses: docker/setup-buildx-action@v1
      - name: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}
      - name: Get kernel version
        run: echo "VERSION=$(uname --kernel-release)" >> ${GITHUB_ENV}
      - name: discoverer
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            TOKEN=${{ secrets.GHCR }}
            VERSION=${{ env.VERSION }}
            COMMIT=${{ github.sha }}
          tags: ghcr.io/${{ env.IMAGE }}:${{ github.sha }}
          push: true
      - name: revise occurrences of the image
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"

          for FILENAME in "./README.md" "./docker-compose.yml"
          do
            echo "Replacing: ${IMAGE}"
            sed \
            --in-place \
            "s|${IMAGE}:[0-9a-f]\{40\}|${IMAGE}:${{ github.sha }}|g" \
            ${FILENAME}
            git add ${FILENAME}
          done

          git commit --message "GitHub Actions update image references"
          git push origin main
